# Generated by Django 4.0.4 on 2022-05-01 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_year_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(upload_to='cars_images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_created',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(2022), django.core.validators.MinValueValidator(2000)]),
        ),
    ]
