# Generated by Django 4.0.4 on 2022-05-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_car_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
