# Generated by Django 4.0.4 on 2022-04-28 13:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_rentcarusermodel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentcarusermodel',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
